version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: hse-antiplagiat-db
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: hse_antiplagiat
    ports:
      - "5432:5432"
    volumes:
      - postgres_antiplagiat_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U youruser -d hse_antiplagiat"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_antiplagiat_data:
    driver: local