server:
  port: 8081

spring:
  application:
    name: file-storing-service
  datasource:
    url: jdbc:postgresql://localhost:5432/hse_antiplagiat
    username: youruser
    password: yourpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

file:
  upload-dir: ./filestore_data_prod

analysis-service:
  url: http://localhost:8082/api/v1/analysis

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method 
  
logging:
  level:
    com.hse.filestoringservice: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE